---
name: releaser

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v5
        with:
          go-version: 1.19
      - uses: goreleaser/goreleaser-action@v5
        id: releaser
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
      - run: |
          echo "binary=$(jq -r '.[] | select(.name == "mattd" and .goos == "linux" and .goarch == "amd64" and .goamd64 == "v1") | .path' ./dist/artifacts.json)" >> $GITHUB_OUTPUT
        id: binary
      - uses: actions/upload-artifact@v4
        with:
          name: mattd
          path: ${{ steps.binary.outputs.binary }}
          retention-days: 1

  help:
    runs-on: ubuntu-latest
    needs: goreleaser
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: mattd
          path: bin/
      - run: |
          chmod 0755 bin/mattd
          echo "./bin" >> $GITHUB_PATH
      - uses: charmbracelet/vhs-action@v2
        with:
          path: "tapes/help.tape"
          install-fonts: true
      - uses: actions/upload-artifact@v4
        with:
          name: help
          path: gifs/help.gif
          retention-days: 1
  version:
    runs-on: ubuntu-latest
    needs: goreleaser
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: mattd
          path: bin/
      - run: |
          chmod 0755 bin/mattd
          echo "./bin" >> $GITHUB_PATH
      - uses: charmbracelet/vhs-action@v2
        with:
          path: "tapes/version.tape"
          install-fonts: true
      - uses: actions/upload-artifact@v4
        with:
          name: version
          path: gifs/version.gif
          retention-days: 1

  init:
    runs-on: ubuntu-latest
    needs: goreleaser
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: mattd
          path: bin/
      - run: |
          chmod 0755 bin/mattd
          echo "./bin" >> $GITHUB_PATH
      - uses: charmbracelet/vhs-action@v2
        with:
          path: "tapes/init.tape"
          install-fonts: true
      - uses: actions/upload-artifact@v4
        with:
          name: init
          path: gifs/init.gif
          retention-days: 1
  completion:
    runs-on: ubuntu-latest
    needs: goreleaser
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: mattd
          path: bin/
      - run: |
          chmod 0755 bin/mattd
          echo "./bin" >> $GITHUB_PATH
      - uses: charmbracelet/vhs-action@v2
        with:
          path: "tapes/completion.tape"
          install-fonts: true
      - uses: actions/upload-artifact@v4
        with:
          name: completion
          path: gifs/completion.gif
          retention-days: 1
  push:
    runs-on: ubuntu-latest
    needs: [completion, help, version, init]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: completion
          path: gifs/
      - uses: actions/download-artifact@v4
        with:
          name: help
          path: gifs/
      - uses: actions/download-artifact@v4
        with:
          name: init
          path: gifs/
      - uses: actions/download-artifact@v4
        with:
          name: version
          path: gifs/
      - uses: stefanzweifel/git-auto-commit-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: "chore: updated generated vhs gifs"
          branch: main
          commit_user_name: vhs-action 📼
          commit_user_email: actions@github.com
          commit_author: vhs-action 📼 <actions@github.com>
          file_pattern: "*.gif"
